#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define LONG_TAPPING_TERM 25
#define TAPPING_TERM_PER_KEY

#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define EE_HANDS
