#pragma once
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY


#undef TAPPING_TERM
#define TAPPING_TERM 100
#define LONG_TAPPING_TERM 50
#define TAPPING_TERM_PER_KEY

#define PERMISSIVE_HOLD_PER_KEY
//#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define EE_HANDS
