#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define LONG_TAPPING_TERM 50

#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY

#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY

#define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY

#define RETRO_TAPPING
#define RETRO_TAPPING_PER_KEY

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define EE_HANDS
